_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 3
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.10
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
batch_size:
    value: 100
data_dim:
    value: 5
epochs:
    value: 500
hidden_dim:
    value: 10
learning_rate:
    value: 0.01
seq_length:
    value: 7
